# Generated by Django 5.0.7 on 2024-08-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='clients.person'),
        ),
    ]
